stages:
  - build
  - image
  - deploy

variables:
  GCP_PROJECT_ID: $GCP_PROJECT_ID
  GOOGLE_APPLICATION_CREDENTIALS: /secrets/gcp-key.json
  IMAGE_NAME: development
  IMAGE_TAG: latest

# Using node:18-alpine for the build stage
build:
  stage: build
  image: node:18-alpine
  tags:
    - dalfcs_docker_kvm
  script:
    - cd frontend || exit 1  # Change directory or exit with error
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/build/

# Using google/cloud-sdk:slim for the deploy stage
deploy:
  stage: deploy
  image: google/cloud-sdk:slim
  before_script:
    - pwd
    - ls
    - mkdir -p /secrets
    - echo $GCP_SERVICE_ACCOUNT_KEY > /secrets/gcp-key.json || (echo "Failed to decode base64"; exit 1)
    - ls /secrets
    - cat /secrets/gcp-key.json
    - wc -l /secrets/gcp-key.json
    - apt-get update && apt-get install -y python3 python3-pip
    - gcloud auth activate-service-account --key-file /secrets/gcp-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud services enable run.googleapis.com
  script:
    - cd frontend
    - gcloud builds submit --tag gcr.io/$GCP_PROJECT_ID/dalvacationhome
    - gcloud run deploy dalvacationhome --image gcr.io/$GCP_PROJECT_ID/dalvacationhome --platform managed --region us-central1 --allow-unauthenticated --port 8080
  only:
    - main
